[package]
name = "rtasks"
version = "0.1.4"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
directories = "5"
eframe = "0.27"
egui = "0.27"
global-hotkey = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tray-icon = "0.22"
ulid = "1"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Pipes",
] }
